#!/data/data/com.termux/files/usr/bin/bash


checkdependencies()
{
    if [ -e ~/../usr/bin/java ] && [ -e ~/../usr/bin/python ] && [ -e ~/../usr/bin/wget ] && [ -e ~/../usr/bin/dialog ] && [ -e ~/../usr/bin/tput ] && [ -e ~/../usr/bin/jq ] && [ "$(find ~/../usr/lib/ -name "wheel" | wc -l)" != "0" ] && [ "$(find ~/../usr/lib/ -name "requests" | wc -l)" != "0" ] && [ "$(find ~/../usr/lib/ -name "bs4" | wc -l)" != "0" ] && [ -e ~/../usr/bin/revancify ]
    then
        return 0
    else
        return 1
    fi
}

installdependencies()
{
    echo "Installing dependencies..."
    sleep 0.5s
    git pull
    pkg update -y &&
    pkg install tsu python openjdk-17 wget ncurses-utils dialog jq -y &&
    pip install --upgrade pip &&
    pip install wheel &&
    pip install requests bs4 &&
    cp dialog-config.txt ~/.dialogrc
    sed -i '/allow-external-apps/s/# //' ~/.termux/termux.properties &&
    echo "Dependencies installed successfully."
}

checkrevancify()
{
    if cd ~/storage/Revancify > /dev/null 2>&1 
    then
        return 0
    else
        echo "Revancify is not installed"
        exit
    fi
}

if ping -c 1 google.com > /dev/null 2>&1
then
    checkrevancify
    if checkdependencies
    then
        tput civis
        rm -rf ./*cache
        git checkout . > /dev/null 2>&1
        git pull
        cp dialog-config.txt ~/.dialogrc
        cp revancify ~/../usr/bin/revancify
        bash main.sh
    else
        cp revancify ~/../usr/bin/revancify
        installdependencies &&
        tput civis &&
        bash main.sh
        cd ~
    fi
else
    checkrevancify
    if checkdependencies
    then
        tput civis &&
        rm -rf ./*cache
        tput civis &&
        bash main.sh
        cd ~
    else
        cp revancify ~/../usr/bin/revancify
        echo "Dependencies not installed. Run again with internet connection."
    fi
fi
